source 'https://rubygems.org'

gem 'sinatra'
gem 'pg'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sinatra-flash'
gem 'sinatra-redirect-with-flash'
gem 'rake'

group :test, :development do
  gem 'rspec'
  gem 'pry'
end
